# This is a basic workflow to help you get started with Actions

name: databricks-import-directory

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
        
        with:
          databricks-host: https://adb-2803406509287793.13.cloud.databricks.com
          databricks-token: dapidd41db34179d5c268204387c7ab3ecfb-3
          local-path: ./https://adb-2803406509287793.13.azuredatabricks.net/?o=2803406509287793#notebook/2953847444847021/command/2953847444847022
          remote-path: /https://adb-2803406509287793.13.azuredatabricks.net/?o=2803406509287793#notebook/2311431816408714/command/2311431816408715
